name: erc20
description: A wrap of the erc20 contract for dart/flutter.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web3dart: ^2.0.0-dev
  pedantic: ^1.8.0
  meta: ^1.1.8

dev_dependencies:
  test: ^1.6.0
